export const SIDEBAR_LEFT_OPEN = 'SIDEBAR_KEFT_OPEN';
export const SIDEBAR_LEFT_CLOSE = 'SIDEBAR_LEFT_CLOSE';
export const SIDEBAR_RIGHT_OPEN = 'SIDEBAR_RIGHT_OPEN';
export const SIDEBAR_RIGHT_CLOSE = 'SIDEBAR_RIGHT_CLOSE';
